#!/usr/bin/bash
wget -O playlist.m3u8 "http://81.211.33.93/hls-live3/streams/1tv-orbit-plus-4/1tv-orbit-plus-45.m3u8?cdn=https://edge1.1internet.tv&s=aM4s4MMZPNh8OET2gkXlXcG0cbRkNkYPVVDwPLf%2F5sgTwohj0HWKGEDMtNHTMxeRo7n0T8Qi%2FwJEMC2%2BNwNMFCowbWPZ70RG%2FUkEIMYKAyw%3D" --header "User-Agent: Wget/1.21.4"||exit 1
a=($(cat playlist.m3u8|grep -i "\.ts"|tail -n 1|sed "s/\//\n/gI"|tail -n 1|sed "s/-/\n/gI;s/_/\n/gI;s/\./\n/gI"))
b=$(echo ${a[4]}|head -c 8|tail -c 2)
c=$(echo ${a[4]}|head -c 11|tail -c 2)
d=$(echo ${a[4]}|head -c 13|tail -c 2)
e=$(echo ${a[4]}|head -c 15|tail -c 2)
f=$(echo ${a[6]})
./download.sh $b $c $d $e $f
